steps:
  - id: 'Executando go unit test'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v', './src/loop']
    env: ['GOPATH=.']

  - id: 'Executando go build'
    name: 'gcr.io/cloud-builders/go'
    env: ['GOPATH=.', 'CGO_ENABLED=0', 'GOOS=linux','GOARCH=amd64']
    args: ['build', '-o','./src/loop', './src/loop']

  - id: "Gerando a tag da aplicação para DockerHub"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t','leorrodrigues/go-hpa','.']

  - id: "Gerando a tag da aplicação para o Registry"
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'leorrodrigues/go-hpa', 'grc.io/$PROJECT_ID/go-hpa:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=leorrodrigues --password=$$PASSWORD']
    secretEnv: ['PASSWORD']
  
  - id: "Executando o push da imagem no DockerHub"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'leorrodrigues/go-hpa']

  - id: "Executando o push da imagem no Registry"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gpc.io/$PROJECT_ID/go-hpa:$SHORT_SHA']
  
secrets:
- kmsKeyName: projects/iniciando-ci/locations/global/keyRings/fullcycle/cryptoKeys/dockerhub-secret
  secretEnv:
    PASSWORD: 'CiQANp9r3Ynf1DDyb/RY0rCaYY+klJ+WRoqp/+hUFTYpe9KV1OASNQBo6N+GRHqdzDnWTbKYeIdIoQa0MqA7ddlvtjJqceqop4aEIP085R3Jv4BwR0yOiOWo4Pme'
