steps:
  - id: 'Executando go unit test'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v', './src/loop']
    env: ['GOPATH=.']

  - id: 'Executando go build'
    name: 'gcr.io/cloud-builders/go'
    env: ['GOPATH=.', 'CGO_ENABLED=0', 'GOOS=linux','GOARCH=amd64']
    args: ['build', '-o','./src/loop', './src/loop']
